/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QaRouteImport } from './routes/qa'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIdRouteImport } from './routes/qa.$id'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as AccommodationIdRouteImport } from './routes/accommodation.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated.my-listings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedQaNewRouteImport } from './routes/_authenticated.qa.new'
import { Route as AuthenticatedMarketplaceNewRouteImport } from './routes/_authenticated.marketplace.new'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated.jobs.new'
import { Route as AuthenticatedCommunitiesNewRouteImport } from './routes/_authenticated.communities.new'
import { Route as AuthenticatedAccommodationNewRouteImport } from './routes/_authenticated.accommodation.new'
import { Route as AuthenticatedMarketplaceIdEditRouteImport } from './routes/_authenticated.marketplace.$id.edit'
import { Route as AuthenticatedJobsIdEditRouteImport } from './routes/_authenticated.jobs.$id.edit'
import { Route as AuthenticatedAccommodationIdEditRouteImport } from './routes/_authenticated.accommodation.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIdRoute = QaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QaRoute,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunitiesRoute,
} as any)
const AccommodationIdRoute = AccommodationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccommodationRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaNewRoute = AuthenticatedQaNewRouteImport.update({
  id: '/qa/new',
  path: '/qa/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceNewRoute =
  AuthenticatedMarketplaceNewRouteImport.update({
    id: '/marketplace/new',
    path: '/marketplace/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunitiesNewRoute =
  AuthenticatedCommunitiesNewRouteImport.update({
    id: '/communities/new',
    path: '/communities/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccommodationNewRoute =
  AuthenticatedAccommodationNewRouteImport.update({
    id: '/accommodation/new',
    path: '/accommodation/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceIdEditRoute =
  AuthenticatedMarketplaceIdEditRouteImport.update({
    id: '/marketplace/$id/edit',
    path: '/marketplace/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsIdEditRoute = AuthenticatedJobsIdEditRouteImport.update({
  id: '/jobs/$id/edit',
  path: '/jobs/$id/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccommodationIdEditRoute =
  AuthenticatedAccommodationIdEditRouteImport.update({
    id: '/accommodation/$id/edit',
    path: '/accommodation/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/qa': typeof QaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/qa/$id': typeof QaIdRoute
  '/accommodation/new': typeof AuthenticatedAccommodationNewRoute
  '/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/qa/new': typeof AuthenticatedQaNewRoute
  '/accommodation/$id/edit': typeof AuthenticatedAccommodationIdEditRoute
  '/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
  '/marketplace/$id/edit': typeof AuthenticatedMarketplaceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/qa': typeof QaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/qa/$id': typeof QaIdRoute
  '/accommodation/new': typeof AuthenticatedAccommodationNewRoute
  '/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/qa/new': typeof AuthenticatedQaNewRoute
  '/accommodation/$id/edit': typeof AuthenticatedAccommodationIdEditRoute
  '/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
  '/marketplace/$id/edit': typeof AuthenticatedMarketplaceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accommodation': typeof AccommodationRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/qa': typeof QaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/qa/$id': typeof QaIdRoute
  '/_authenticated/accommodation/new': typeof AuthenticatedAccommodationNewRoute
  '/_authenticated/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/_authenticated/qa/new': typeof AuthenticatedQaNewRoute
  '/_authenticated/accommodation/$id/edit': typeof AuthenticatedAccommodationIdEditRoute
  '/_authenticated/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
  '/_authenticated/marketplace/$id/edit': typeof AuthenticatedMarketplaceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodation'
    | '/communities'
    | '/jobs'
    | '/login'
    | '/marketplace'
    | '/qa'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/my-listings'
    | '/notifications'
    | '/profile'
    | '/accommodation/$id'
    | '/communities/$slug'
    | '/jobs/$id'
    | '/marketplace/$id'
    | '/qa/$id'
    | '/accommodation/new'
    | '/communities/new'
    | '/jobs/new'
    | '/marketplace/new'
    | '/qa/new'
    | '/accommodation/$id/edit'
    | '/jobs/$id/edit'
    | '/marketplace/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodation'
    | '/communities'
    | '/jobs'
    | '/login'
    | '/marketplace'
    | '/qa'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/my-listings'
    | '/notifications'
    | '/profile'
    | '/accommodation/$id'
    | '/communities/$slug'
    | '/jobs/$id'
    | '/marketplace/$id'
    | '/qa/$id'
    | '/accommodation/new'
    | '/communities/new'
    | '/jobs/new'
    | '/marketplace/new'
    | '/qa/new'
    | '/accommodation/$id/edit'
    | '/jobs/$id/edit'
    | '/marketplace/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accommodation'
    | '/communities'
    | '/jobs'
    | '/login'
    | '/marketplace'
    | '/qa'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-listings'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/accommodation/$id'
    | '/communities/$slug'
    | '/jobs/$id'
    | '/marketplace/$id'
    | '/qa/$id'
    | '/_authenticated/accommodation/new'
    | '/_authenticated/communities/new'
    | '/_authenticated/jobs/new'
    | '/_authenticated/marketplace/new'
    | '/_authenticated/qa/new'
    | '/_authenticated/accommodation/$id/edit'
    | '/_authenticated/jobs/$id/edit'
    | '/_authenticated/marketplace/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccommodationRoute: typeof AccommodationRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  QaRoute: typeof QaRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/$id': {
      id: '/qa/$id'
      path: '/$id'
      fullPath: '/qa/$id'
      preLoaderRoute: typeof QaIdRouteImport
      parentRoute: typeof QaRoute
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/accommodation/$id': {
      id: '/accommodation/$id'
      path: '/$id'
      fullPath: '/accommodation/$id'
      preLoaderRoute: typeof AccommodationIdRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/new': {
      id: '/_authenticated/qa/new'
      path: '/qa/new'
      fullPath: '/qa/new'
      preLoaderRoute: typeof AuthenticatedQaNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/new': {
      id: '/_authenticated/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof AuthenticatedMarketplaceNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communities/new': {
      id: '/_authenticated/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof AuthenticatedCommunitiesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accommodation/new': {
      id: '/_authenticated/accommodation/new'
      path: '/accommodation/new'
      fullPath: '/accommodation/new'
      preLoaderRoute: typeof AuthenticatedAccommodationNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/$id/edit': {
      id: '/_authenticated/marketplace/$id/edit'
      path: '/marketplace/$id/edit'
      fullPath: '/marketplace/$id/edit'
      preLoaderRoute: typeof AuthenticatedMarketplaceIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$id/edit': {
      id: '/_authenticated/jobs/$id/edit'
      path: '/jobs/$id/edit'
      fullPath: '/jobs/$id/edit'
      preLoaderRoute: typeof AuthenticatedJobsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accommodation/$id/edit': {
      id: '/_authenticated/accommodation/$id/edit'
      path: '/accommodation/$id/edit'
      fullPath: '/accommodation/$id/edit'
      preLoaderRoute: typeof AuthenticatedAccommodationIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAccommodationNewRoute: typeof AuthenticatedAccommodationNewRoute
  AuthenticatedCommunitiesNewRoute: typeof AuthenticatedCommunitiesNewRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedMarketplaceNewRoute: typeof AuthenticatedMarketplaceNewRoute
  AuthenticatedQaNewRoute: typeof AuthenticatedQaNewRoute
  AuthenticatedAccommodationIdEditRoute: typeof AuthenticatedAccommodationIdEditRoute
  AuthenticatedJobsIdEditRoute: typeof AuthenticatedJobsIdEditRoute
  AuthenticatedMarketplaceIdEditRoute: typeof AuthenticatedMarketplaceIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAccommodationNewRoute: AuthenticatedAccommodationNewRoute,
  AuthenticatedCommunitiesNewRoute: AuthenticatedCommunitiesNewRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedMarketplaceNewRoute: AuthenticatedMarketplaceNewRoute,
  AuthenticatedQaNewRoute: AuthenticatedQaNewRoute,
  AuthenticatedAccommodationIdEditRoute: AuthenticatedAccommodationIdEditRoute,
  AuthenticatedJobsIdEditRoute: AuthenticatedJobsIdEditRoute,
  AuthenticatedMarketplaceIdEditRoute: AuthenticatedMarketplaceIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AccommodationRouteChildren {
  AccommodationIdRoute: typeof AccommodationIdRoute
}

const AccommodationRouteChildren: AccommodationRouteChildren = {
  AccommodationIdRoute: AccommodationIdRoute,
}

const AccommodationRouteWithChildren = AccommodationRoute._addFileChildren(
  AccommodationRouteChildren,
)

interface CommunitiesRouteChildren {
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesSlugRoute: CommunitiesSlugRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface QaRouteChildren {
  QaIdRoute: typeof QaIdRoute
}

const QaRouteChildren: QaRouteChildren = {
  QaIdRoute: QaIdRoute,
}

const QaRouteWithChildren = QaRoute._addFileChildren(QaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccommodationRoute: AccommodationRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  QaRoute: QaRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
